services:

  nginx:
    restart: always
    container_name: nginx
    build:
      dockerfile: Dockerfile
      context: ./requirements/nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress

  wordpress:
    restart: always
    container_name: wordpress
    build:
      dockerfile: Dockerfile
      context: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    expose:
      - "9000"
    depends_on:
      - mariadb

  mariadb:
    restart: always
    container_name: mariadb
    build:
      dockerfile: Dockerfile
      context: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    ports:
      - "3306"

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress